name: setup infrastructure - logicapps

on: push

env:
  # Common variables
  AZURE_RESOURCE_GROUP: "datamindslogicapps"
  LOCATION: "uksouth"
  # Enable this variable to allow set-env (https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)
  #ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  bicep-build-and-deploy:
    name: bicep build and deploy
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Transpile bicep file into ARM template
      - name: Build ARM Template from bicep file
        run: |
          az bicep build --file ./realtimepipeline-logicapps.bicep

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Create resource group
      - name: Create Resource Group
        run: |
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.LOCATION }}

      # Get Subscription ID
      - name: Get Subscription ID
        run: |
          subscription=$(az account show --query "id" -o tsv)
          echo "subscription=$subscription" >> $GITHUB_ENV
          echo "Retrieved subscription ID: $subscription"

      # Deploy ARM template
      - name: Deploy ARM template
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{env.subscription}}
          resourceGroupName: ${{env.AZURE_RESOURCE_GROUP}}
          template: ./realtimepipeline-logicapps.json